using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

namespace UlObservableGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class UlObservableGenerator : IIncrementalGenerator
{
    const string Ns = "Ulenv";
    const string Atr = "UlObservableAttribute";
    const string AtrDisp = $"{Ns}.{Atr}";
    const string AtrMethod = "UlObservableMethodAttribute";
    const string AtrMethodDisp = $"{Ns}.{AtrMethod}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx => ctx.AddSource($"{Ns}.UlObservable.cs", PostAtr()));

        var source = context.SyntaxProvider.ForAttributeWithMetadataName(
            AtrDisp,
            static (node, token) => node is InterfaceDeclarationSyntax,
            static (context, token) => context
        );
        context.RegisterSourceOutput(source, Emit);
    }

    static void Emit(SourceProductionContext context, GeneratorAttributeSyntaxContext source)
    {
        var typeSymbol = (INamedTypeSymbol)source.TargetSymbol;
        var typeNode = (TypeDeclarationSyntax)source.TargetNode;
        var className = typeSymbol.Name;

        var accessibility = typeSymbol.DeclaredAccessibility switch
        {
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.Internal => "internal",
            Accessibility.Public => "public",
            _ => null,
        };
        if (string.IsNullOrEmpty(accessibility))
        {
            context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.E0001, typeNode.Identifier.GetLocation(), typeSymbol.Name));
            return;
        }
        if (!typeNode.Modifiers.Any(x => x.IsKind(SyntaxKind.PartialKeyword)))
        {
            context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.E0002, typeNode.Identifier.GetLocation(), typeSymbol.Name));
            return;
        }

        var sb = new StringBuilder();
        foreach (var atr in typeSymbol.GetAttributes())
        {
            if (atr?.AttributeClass?.ToDisplayString() != AtrMethodDisp) continue;
            var name = atr.ConstructorArguments[0].Value!.ToString();
            var type = atr.ConstructorArguments[1].Value!.ToString();
            if (sb.Length > 0) sb.Append('\n');
            sb.Append($$"""    void {{name}}<T>({{type}} identifier) where T : unmanaged, IUlCallback<{{type}}>;""");
        }

        if (sb.Length <= 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.E0003, typeNode.Identifier.GetLocation(), typeSymbol.Name));
            return;
        }

        var isNamespace = !typeSymbol.ContainingNamespace.IsGlobalNamespace;

        context.AddSource($"{className}.UlObservable.g.cs", $$"""
// <auto-generated/>
using Ulenv;
{{(isNamespace ? $$"""namespace {{typeSymbol.ContainingNamespace}} {""" : "")}}
{{accessibility}} partial interface {{className}}
{
{{sb}}
}
{{(isNamespace ? "}" : "")}}
""");
    }

    static string PostAtr()
    {
        return $$"""
using System;
namespace {{Ns}}
{
    /// <summary>
    /// This is an attribute for recognizing '{{AtrMethod}}'.
    /// </summary>
    [AttributeUsage(AttributeTargets.Interface, AllowMultiple = false)]
    internal sealed class {{Atr}} : Attribute
    {
        public {{Atr}}() { }
    }

    /// <summary>
    /// The following declarations are automatically implemented.
    /// <code>
    /// void 'methodName' &lt;T> ('argType' identifier) where T : unmanaged, IUlCallback &lt;'argType'>;
    /// </code>
    /// </summary>
    [AttributeUsage(AttributeTargets.Interface, AllowMultiple = true)]
    internal sealed class {{AtrMethod}} : Attribute
    {
        public {{AtrMethod}}(string methodName, Type argType) { }
    }
}
""";
    }
}
