using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

namespace UlCallbackGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class UlCallbackGenerator : IIncrementalGenerator
{
    const string Ns = "Ulenv";
    const string Atr = "UlCallbackAttribute";
    const string AtrDisp = $"{Ns}.{Atr}";
    const string M_Enter = "PointerEnterAttribute";
    const string M_Exit = "PointerExitAttribute";
    const string M_Down = "PointerDownAttribute";
    const string M_Up = "PointerUpAttribute";
    const string M_Click = "PointerClickAttribute";
    const string M_EnterDisp = $"{Ns}.{M_Enter}";
    const string M_ExitDisp = $"{Ns}.{M_Exit}";
    const string M_DownDisp = $"{Ns}.{M_Down}";
    const string M_UpDisp = $"{Ns}.{M_Up}";
    const string M_ClickDisp = $"{Ns}.{M_Click}";
    static readonly HashSet<string> M_Set = new() { M_EnterDisp, M_ExitDisp, M_DownDisp, M_UpDisp, M_ClickDisp, };
    static readonly Dictionary<string, string> SwitchMap = new()
    {
        { M_EnterDisp, "        case 1: (obj as {0}).{1}({2}); break;" },
        { M_ExitDisp, "        case 2: (obj as {0}).{1}({2}); break;" },
        { M_DownDisp, "        case 3: (obj as {0}).{1}({2}); break;" },
        { M_UpDisp, "        case 4: (obj as {0}).{1}({2}); break;" },
        { M_ClickDisp, "        case 5: (obj as {0}).{1}({2}); break;" },
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx => ctx.AddSource($"{Ns}.UlCallback.cs", PostAtr()));

        var source = context.SyntaxProvider.ForAttributeWithMetadataName(
            AtrDisp,
            static (node, token) => node is ClassDeclarationSyntax,
            static (context, token) => context
        );
        context.RegisterSourceOutput(source, Emit);
    }

    static void Emit(SourceProductionContext context, GeneratorAttributeSyntaxContext source)
    {
        var typeSymbol = (INamedTypeSymbol)source.TargetSymbol;
        var typeNode = (TypeDeclarationSyntax)source.TargetNode;
        var className = typeSymbol.Name;

        var accessibility = typeSymbol.DeclaredAccessibility switch
        {
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.Internal => "internal",
            Accessibility.Public => "public",
            _ => null,
        };
        if (string.IsNullOrEmpty(accessibility))
        {
            context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.E0001, typeNode.Identifier.GetLocation(), typeSymbol.Name));
            return;
        }
        if (!typeNode.Modifiers.Any(x => x.IsKind(SyntaxKind.PartialKeyword)))
        {
            context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.E0002, typeNode.Identifier.GetLocation(), typeSymbol.Name));
            return;
        }

        var map = new Dictionary<string, StringBuilder>();
        foreach (var member in typeSymbol.GetMembers())
        {
            if (member is not IMethodSymbol method || method.Parameters.Length > 1) continue;
            foreach (var atr in member.GetAttributes())
            {
                if (atr == null || atr?.ConstructorArguments.Length != 1) continue;
                var disp = atr.AttributeClass?.ToDisplayString();
                if (disp == null || string.IsNullOrEmpty(disp) || !M_Set.Contains(disp)) continue;
                var symbol = atr.ConstructorArguments[0].Value!.ToString();
                if (!map.TryGetValue(symbol, out var sb))
                {
                    sb = new();
                    map.Add(symbol, sb);
                }
                if (sb.Length > 0) sb.Append('\n');
                var arg = method.Parameters.Length == 0
                    ? string.Empty
                    : $"args as {method.Parameters[0].Type.ToDisplayString()}";
                sb.Append(string.Format(SwitchMap[disp], className, method.Name, arg));
            }
        }

        if (map.Count == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.E0003, typeNode.Identifier.GetLocation(), typeSymbol.Name));
            return;
        }

        var isNamespace = !typeSymbol.ContainingNamespace.IsGlobalNamespace;

        context.AddSource($"{className}.UlCallback.g.cs", $$"""
// <auto-generated/>
using Ulenv;
{{(isNamespace ? $$"""namespace {{typeSymbol.ContainingNamespace}} {""" : "")}}
{{accessibility}} partial class {{className}}
{
{{string.Join("\n", map.Select(x => $$"""
  readonly struct {{x.Key}}Callback : IUlCallback
  {
    public void Recept(object obj, object args, int code)
    {
      switch (code)
      {
{{x.Value}}
      }
    }
  }
"""))}}
}
{{(isNamespace ? "}" : "")}}
""");
    }

    static string PostAtr()
    {
        return $$"""
using System;
namespace {{Ns}}
{
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    internal sealed class {{Atr}} : Attribute
    {
        public {{Atr}}() { }
    }

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    internal sealed class {{M_Enter}} : Attribute
    {
        public {{M_Enter}}(string symbol) { }
    }

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    internal sealed class {{M_Exit}} : Attribute
    {
        public {{M_Exit}}(string symbol) { }
    }

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    internal sealed class {{M_Down}} : Attribute
    {
        public {{M_Down}}(string symbol) { }
    }

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    internal sealed class {{M_Up}} : Attribute
    {
        public {{M_Up}}(string symbol) { }
    }

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    internal sealed class {{M_Click}} : Attribute
    {
        public {{M_Click}}(string symbol) { }
    }
}
""";
    }
}
